// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: dexon_fleetcontrol.proto

package fleetcontrolv1

import (
	agentv1 "github.com/anandrkskd/dexon/proto/agentv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAvailableHostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableHostsRequest) Reset() {
	*x = GetAvailableHostsRequest{}
	mi := &file_dexon_fleetcontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableHostsRequest) ProtoMessage() {}

func (x *GetAvailableHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_fleetcontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableHostsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableHostsRequest) Descriptor() ([]byte, []int) {
	return file_dexon_fleetcontrol_proto_rawDescGZIP(), []int{0}
}

type HostList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*HostSummary         `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostList) Reset() {
	*x = HostList{}
	mi := &file_dexon_fleetcontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostList) ProtoMessage() {}

func (x *HostList) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_fleetcontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostList.ProtoReflect.Descriptor instead.
func (*HostList) Descriptor() ([]byte, []int) {
	return file_dexon_fleetcontrol_proto_rawDescGZIP(), []int{1}
}

func (x *HostList) GetHosts() []*HostSummary {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type HostSummary struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	HostId                string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	CpuCores              int32                  `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes           int64                  `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	HyperthreadingEnabled bool                   `protobuf:"varint,4,opt,name=hyperthreading_enabled,json=hyperthreadingEnabled,proto3" json:"hyperthreading_enabled,omitempty"`
	LastHeartbeatUnix     int64                  `protobuf:"varint,5,opt,name=last_heartbeat_unix,json=lastHeartbeatUnix,proto3" json:"last_heartbeat_unix,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HostSummary) Reset() {
	*x = HostSummary{}
	mi := &file_dexon_fleetcontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSummary) ProtoMessage() {}

func (x *HostSummary) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_fleetcontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSummary.ProtoReflect.Descriptor instead.
func (*HostSummary) Descriptor() ([]byte, []int) {
	return file_dexon_fleetcontrol_proto_rawDescGZIP(), []int{2}
}

func (x *HostSummary) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HostSummary) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HostSummary) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *HostSummary) GetHyperthreadingEnabled() bool {
	if x != nil {
		return x.HyperthreadingEnabled
	}
	return false
}

func (x *HostSummary) GetLastHeartbeatUnix() int64 {
	if x != nil {
		return x.LastHeartbeatUnix
	}
	return 0
}

// Scheduler has already made the placement decision; this just tells
// Fleet manager where to send it. Fleet manager still validates the
// host is still connected/available before forwarding -- a host can
// go stale between GetAvailableHosts and Dispatch.
type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Vm            *agentv1.VMSpec        `protobuf:"bytes,2,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_dexon_fleetcontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_fleetcontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_dexon_fleetcontrol_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *DispatchRequest) GetVm() *agentv1.VMSpec {
	if x != nil {
		return x.Vm
	}
	return nil
}

// Acknowledges only that Fleet manager accepted responsibility for the
// command (host was reachable, command was sent). It does NOT mean the
// VM is running yet -- that outcome arrives later via CommandResult on
// the agent stream, and Fleet manager writes it to the DB from there.
// The client learns the real outcome by polling GET /vms/{id}, not
// through this RPC.
type DispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // e.g. host disconnected between selection and dispatch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_dexon_fleetcontrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_fleetcontrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_dexon_fleetcontrol_proto_rawDescGZIP(), []int{4}
}

func (x *DispatchResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DispatchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RequestDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDeleteRequest) Reset() {
	*x = RequestDeleteRequest{}
	mi := &file_dexon_fleetcontrol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeleteRequest) ProtoMessage() {}

func (x *RequestDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_fleetcontrol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeleteRequest.ProtoReflect.Descriptor instead.
func (*RequestDeleteRequest) Descriptor() ([]byte, []int) {
	return file_dexon_fleetcontrol_proto_rawDescGZIP(), []int{5}
}

func (x *RequestDeleteRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// Same caveat as DispatchResponse: accepted means the delete was
// relayed (or, if the VM had no host yet, marked deleted immediately).
// It is not a guarantee the VM is gone -- poll GET /vms/{id} for that.
type RequestDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDeleteResponse) Reset() {
	*x = RequestDeleteResponse{}
	mi := &file_dexon_fleetcontrol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeleteResponse) ProtoMessage() {}

func (x *RequestDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_fleetcontrol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeleteResponse.ProtoReflect.Descriptor instead.
func (*RequestDeleteResponse) Descriptor() ([]byte, []int) {
	return file_dexon_fleetcontrol_proto_rawDescGZIP(), []int{6}
}

func (x *RequestDeleteResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RequestDeleteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_dexon_fleetcontrol_proto protoreflect.FileDescriptor

const file_dexon_fleetcontrol_proto_rawDesc = "" +
	"\n" +
	"\x18dexon_fleetcontrol.proto\x12\x15dexon.fleetcontrol.v1\x1a\x11dexon_agent.proto\"\x1a\n" +
	"\x18GetAvailableHostsRequest\"D\n" +
	"\bHostList\x128\n" +
	"\x05hosts\x18\x01 \x03(\v2\".dexon.fleetcontrol.v1.HostSummaryR\x05hosts\"\xcd\x01\n" +
	"\vHostSummary\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x03R\vmemoryBytes\x125\n" +
	"\x16hyperthreading_enabled\x18\x04 \x01(\bR\x15hyperthreadingEnabled\x12.\n" +
	"\x13last_heartbeat_unix\x18\x05 \x01(\x03R\x11lastHeartbeatUnix\"R\n" +
	"\x0fDispatchRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12&\n" +
	"\x02vm\x18\x02 \x01(\v2\x16.dexon.agent.v1.VMSpecR\x02vm\"S\n" +
	"\x10DispatchResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"+\n" +
	"\x14RequestDeleteRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"X\n" +
	"\x15RequestDeleteResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xbe\x02\n" +
	"\fFleetControl\x12e\n" +
	"\x11GetAvailableHosts\x12/.dexon.fleetcontrol.v1.GetAvailableHostsRequest\x1a\x1f.dexon.fleetcontrol.v1.HostList\x12[\n" +
	"\bDispatch\x12&.dexon.fleetcontrol.v1.DispatchRequest\x1a'.dexon.fleetcontrol.v1.DispatchResponse\x12j\n" +
	"\rRequestDelete\x12+.dexon.fleetcontrol.v1.RequestDeleteRequest\x1a,.dexon.fleetcontrol.v1.RequestDeleteResponseBAZ?github.com/anandrkskd/dexon/proto/fleetcontrolv1;fleetcontrolv1b\x06proto3"

var (
	file_dexon_fleetcontrol_proto_rawDescOnce sync.Once
	file_dexon_fleetcontrol_proto_rawDescData []byte
)

func file_dexon_fleetcontrol_proto_rawDescGZIP() []byte {
	file_dexon_fleetcontrol_proto_rawDescOnce.Do(func() {
		file_dexon_fleetcontrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dexon_fleetcontrol_proto_rawDesc), len(file_dexon_fleetcontrol_proto_rawDesc)))
	})
	return file_dexon_fleetcontrol_proto_rawDescData
}

var file_dexon_fleetcontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dexon_fleetcontrol_proto_goTypes = []any{
	(*GetAvailableHostsRequest)(nil), // 0: dexon.fleetcontrol.v1.GetAvailableHostsRequest
	(*HostList)(nil),                 // 1: dexon.fleetcontrol.v1.HostList
	(*HostSummary)(nil),              // 2: dexon.fleetcontrol.v1.HostSummary
	(*DispatchRequest)(nil),          // 3: dexon.fleetcontrol.v1.DispatchRequest
	(*DispatchResponse)(nil),         // 4: dexon.fleetcontrol.v1.DispatchResponse
	(*RequestDeleteRequest)(nil),     // 5: dexon.fleetcontrol.v1.RequestDeleteRequest
	(*RequestDeleteResponse)(nil),    // 6: dexon.fleetcontrol.v1.RequestDeleteResponse
	(*agentv1.VMSpec)(nil),           // 7: dexon.agent.v1.VMSpec
}
var file_dexon_fleetcontrol_proto_depIdxs = []int32{
	2, // 0: dexon.fleetcontrol.v1.HostList.hosts:type_name -> dexon.fleetcontrol.v1.HostSummary
	7, // 1: dexon.fleetcontrol.v1.DispatchRequest.vm:type_name -> dexon.agent.v1.VMSpec
	0, // 2: dexon.fleetcontrol.v1.FleetControl.GetAvailableHosts:input_type -> dexon.fleetcontrol.v1.GetAvailableHostsRequest
	3, // 3: dexon.fleetcontrol.v1.FleetControl.Dispatch:input_type -> dexon.fleetcontrol.v1.DispatchRequest
	5, // 4: dexon.fleetcontrol.v1.FleetControl.RequestDelete:input_type -> dexon.fleetcontrol.v1.RequestDeleteRequest
	1, // 5: dexon.fleetcontrol.v1.FleetControl.GetAvailableHosts:output_type -> dexon.fleetcontrol.v1.HostList
	4, // 6: dexon.fleetcontrol.v1.FleetControl.Dispatch:output_type -> dexon.fleetcontrol.v1.DispatchResponse
	6, // 7: dexon.fleetcontrol.v1.FleetControl.RequestDelete:output_type -> dexon.fleetcontrol.v1.RequestDeleteResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dexon_fleetcontrol_proto_init() }
func file_dexon_fleetcontrol_proto_init() {
	if File_dexon_fleetcontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dexon_fleetcontrol_proto_rawDesc), len(file_dexon_fleetcontrol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dexon_fleetcontrol_proto_goTypes,
		DependencyIndexes: file_dexon_fleetcontrol_proto_depIdxs,
		MessageInfos:      file_dexon_fleetcontrol_proto_msgTypes,
	}.Build()
	File_dexon_fleetcontrol_proto = out.File
	file_dexon_fleetcontrol_proto_goTypes = nil
	file_dexon_fleetcontrol_proto_depIdxs = nil
}
