// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: dexon_fleetcontrol.proto

package fleetcontrolv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetControl_GetAvailableHosts_FullMethodName = "/dexon.fleetcontrol.v1.FleetControl/GetAvailableHosts"
	FleetControl_Dispatch_FullMethodName          = "/dexon.fleetcontrol.v1.FleetControl/Dispatch"
	FleetControl_RequestDelete_FullMethodName     = "/dexon.fleetcontrol.v1.FleetControl/RequestDelete"
)

// FleetControlClient is the client API for FleetControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FleetControl is Fleet manager's internal-facing service. Unlike the
// agent-facing FleetManager service (long-lived stream, agent-initiated),
// this is a plain request/response gRPC service with two callers:
//   - Scheduler: GetAvailableHosts (placement input) and Dispatch
//     (send a placement decision down to an agent).
//   - API:       RequestDelete only -- no placement decision needed,
//     so it skips the Scheduler entirely (see design notes).
//
// Fleet manager remains the only writer of VM status regardless of
// which of these two callers triggered the request.
type FleetControlClient interface {
	GetAvailableHosts(ctx context.Context, in *GetAvailableHostsRequest, opts ...grpc.CallOption) (*HostList, error)
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
	RequestDelete(ctx context.Context, in *RequestDeleteRequest, opts ...grpc.CallOption) (*RequestDeleteResponse, error)
}

type fleetControlClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetControlClient(cc grpc.ClientConnInterface) FleetControlClient {
	return &fleetControlClient{cc}
}

func (c *fleetControlClient) GetAvailableHosts(ctx context.Context, in *GetAvailableHostsRequest, opts ...grpc.CallOption) (*HostList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostList)
	err := c.cc.Invoke(ctx, FleetControl_GetAvailableHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetControlClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, FleetControl_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetControlClient) RequestDelete(ctx context.Context, in *RequestDeleteRequest, opts ...grpc.CallOption) (*RequestDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestDeleteResponse)
	err := c.cc.Invoke(ctx, FleetControl_RequestDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetControlServer is the server API for FleetControl service.
// All implementations must embed UnimplementedFleetControlServer
// for forward compatibility.
//
// FleetControl is Fleet manager's internal-facing service. Unlike the
// agent-facing FleetManager service (long-lived stream, agent-initiated),
// this is a plain request/response gRPC service with two callers:
//   - Scheduler: GetAvailableHosts (placement input) and Dispatch
//     (send a placement decision down to an agent).
//   - API:       RequestDelete only -- no placement decision needed,
//     so it skips the Scheduler entirely (see design notes).
//
// Fleet manager remains the only writer of VM status regardless of
// which of these two callers triggered the request.
type FleetControlServer interface {
	GetAvailableHosts(context.Context, *GetAvailableHostsRequest) (*HostList, error)
	Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error)
	RequestDelete(context.Context, *RequestDeleteRequest) (*RequestDeleteResponse, error)
	mustEmbedUnimplementedFleetControlServer()
}

// UnimplementedFleetControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetControlServer struct{}

func (UnimplementedFleetControlServer) GetAvailableHosts(context.Context, *GetAvailableHostsRequest) (*HostList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableHosts not implemented")
}
func (UnimplementedFleetControlServer) Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedFleetControlServer) RequestDelete(context.Context, *RequestDeleteRequest) (*RequestDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestDelete not implemented")
}
func (UnimplementedFleetControlServer) mustEmbedUnimplementedFleetControlServer() {}
func (UnimplementedFleetControlServer) testEmbeddedByValue()                      {}

// UnsafeFleetControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetControlServer will
// result in compilation errors.
type UnsafeFleetControlServer interface {
	mustEmbedUnimplementedFleetControlServer()
}

func RegisterFleetControlServer(s grpc.ServiceRegistrar, srv FleetControlServer) {
	// If the following call panics, it indicates UnimplementedFleetControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetControl_ServiceDesc, srv)
}

func _FleetControl_GetAvailableHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetControlServer).GetAvailableHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetControl_GetAvailableHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetControlServer).GetAvailableHosts(ctx, req.(*GetAvailableHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetControl_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetControlServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetControl_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetControlServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetControl_RequestDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetControlServer).RequestDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetControl_RequestDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetControlServer).RequestDelete(ctx, req.(*RequestDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetControl_ServiceDesc is the grpc.ServiceDesc for FleetControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dexon.fleetcontrol.v1.FleetControl",
	HandlerType: (*FleetControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailableHosts",
			Handler:    _FleetControl_GetAvailableHosts_Handler,
		},
		{
			MethodName: "Dispatch",
			Handler:    _FleetControl_Dispatch_Handler,
		},
		{
			MethodName: "RequestDelete",
			Handler:    _FleetControl_RequestDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dexon_fleetcontrol.proto",
}
