// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: dexon_agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	HostId string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Metrics
	//	*AgentMessage_Drift
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_dexon_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_dexon_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterHost {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetMetrics() *MetricsReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentMessage) GetDrift() *DriftReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Drift); ok {
			return x.Drift
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterHost `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Metrics struct {
	Metrics *MetricsReport `protobuf:"bytes,4,opt,name=metrics,proto3,oneof"`
}

type AgentMessage_Drift struct {
	Drift *DriftReport `protobuf:"bytes,5,opt,name=drift,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Metrics) isAgentMessage_Payload() {}

func (*AgentMessage_Drift) isAgentMessage_Payload() {}

// Sent once, immediately after the stream opens (and again after any
// reconnect, since the fleet manager treats a reconnect as a new agent
// session until it re-registers).
type RegisterHost struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CpuCores              int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes           int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	HyperthreadingEnabled bool                   `protobuf:"varint,3,opt,name=hyperthreading_enabled,json=hyperthreadingEnabled,proto3" json:"hyperthreading_enabled,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterHost) Reset() {
	*x = RegisterHost{}
	mi := &file_dexon_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHost) ProtoMessage() {}

func (x *RegisterHost) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHost.ProtoReflect.Descriptor instead.
func (*RegisterHost) Descriptor() ([]byte, []int) {
	return file_dexon_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterHost) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *RegisterHost) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *RegisterHost) GetHyperthreadingEnabled() bool {
	if x != nil {
		return x.HyperthreadingEnabled
	}
	return false
}

// Cheap liveness signal. Absence of heartbeats within a timeout is how
// the fleet manager detects a dead/unreachable host.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixTimestamp int64                  `protobuf:"varint,1,opt,name=unix_timestamp,json=unixTimestamp,proto3" json:"unix_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_dexon_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_dexon_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetUnixTimestamp() int64 {
	if x != nil {
		return x.UnixTimestamp
	}
	return 0
}

// Streamed periodically. Carries per-VM and host-level resource usage.
type MetricsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *HostMetrics           `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Vms           []*VMMetrics           `protobuf:"bytes,2,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_dexon_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_dexon_agent_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsReport) GetHost() *HostMetrics {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *MetricsReport) GetVms() []*VMMetrics {
	if x != nil {
		return x.Vms
	}
	return nil
}

type HostMetrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent           float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryAvailableBytes int64                  `protobuf:"varint,2,opt,name=memory_available_bytes,json=memoryAvailableBytes,proto3" json:"memory_available_bytes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HostMetrics) Reset() {
	*x = HostMetrics{}
	mi := &file_dexon_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetrics) ProtoMessage() {}

func (x *HostMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetrics.ProtoReflect.Descriptor instead.
func (*HostMetrics) Descriptor() ([]byte, []int) {
	return file_dexon_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HostMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HostMetrics) GetMemoryAvailableBytes() int64 {
	if x != nil {
		return x.MemoryAvailableBytes
	}
	return 0
}

type VMMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMMetrics) Reset() {
	*x = VMMetrics{}
	mi := &file_dexon_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMMetrics) ProtoMessage() {}

func (x *VMMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMMetrics.ProtoReflect.Descriptor instead.
func (*VMMetrics) Descriptor() ([]byte, []int) {
	return file_dexon_agent_proto_rawDescGZIP(), []int{5}
}

func (x *VMMetrics) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *VMMetrics) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

// Sent when the agent's reconcile loop finds actual state (libvirt)
// doesn't match cached desired state. The agent takes no corrective
// action itself -- it only reports; the fleet manager decides the fix.
type DriftReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MissingVmIds    []string               `protobuf:"bytes,1,rep,name=missing_vm_ids,json=missingVmIds,proto3" json:"missing_vm_ids,omitempty"`          // desired but not running
	UnexpectedVmIds []string               `protobuf:"bytes,2,rep,name=unexpected_vm_ids,json=unexpectedVmIds,proto3" json:"unexpected_vm_ids,omitempty"` // running but not desired
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DriftReport) Reset() {
	*x = DriftReport{}
	mi := &file_dexon_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftReport) ProtoMessage() {}

func (x *DriftReport) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftReport.ProtoReflect.Descriptor instead.
func (*DriftReport) Descriptor() ([]byte, []int) {
	return file_dexon_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DriftReport) GetMissingVmIds() []string {
	if x != nil {
		return x.MissingVmIds
	}
	return nil
}

func (x *DriftReport) GetUnexpectedVmIds() []string {
	if x != nil {
		return x.UnexpectedVmIds
	}
	return nil
}

type FleetCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*FleetCommand_Snapshot
	//	*FleetCommand_CreateVm
	//	*FleetCommand_DeleteVm
	Payload       isFleetCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetCommand) Reset() {
	*x = FleetCommand{}
	mi := &file_dexon_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetCommand) ProtoMessage() {}

func (x *FleetCommand) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetCommand.ProtoReflect.Descriptor instead.
func (*FleetCommand) Descriptor() ([]byte, []int) {
	return file_dexon_agent_proto_rawDescGZIP(), []int{7}
}

func (x *FleetCommand) GetPayload() isFleetCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FleetCommand) GetSnapshot() *DesiredStateSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*FleetCommand_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *FleetCommand) GetCreateVm() *CreateVM {
	if x != nil {
		if x, ok := x.Payload.(*FleetCommand_CreateVm); ok {
			return x.CreateVm
		}
	}
	return nil
}

func (x *FleetCommand) GetDeleteVm() *DeleteVM {
	if x != nil {
		if x, ok := x.Payload.(*FleetCommand_DeleteVm); ok {
			return x.DeleteVm
		}
	}
	return nil
}

type isFleetCommand_Payload interface {
	isFleetCommand_Payload()
}

type FleetCommand_Snapshot struct {
	Snapshot *DesiredStateSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type FleetCommand_CreateVm struct {
	CreateVm *CreateVM `protobuf:"bytes,2,opt,name=create_vm,json=createVm,proto3,oneof"`
}

type FleetCommand_DeleteVm struct {
	DeleteVm *DeleteVM `protobuf:"bytes,3,opt,name=delete_vm,json=deleteVm,proto3,oneof"`
}

func (*FleetCommand_Snapshot) isFleetCommand_Payload() {}

func (*FleetCommand_CreateVm) isFleetCommand_Payload() {}

func (*FleetCommand_DeleteVm) isFleetCommand_Payload() {}

// Full desired-state replace, not incremental. Sent right after a
// successful RegisterHost, and again after any reconnect, so the
// agent's cache can never silently miss a change made while disconnected.
type DesiredStateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VMSpec              `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredStateSnapshot) Reset() {
	*x = DesiredStateSnapshot{}
	mi := &file_dexon_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredStateSnapshot) ProtoMessage() {}

func (x *DesiredStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredStateSnapshot.ProtoReflect.Descriptor instead.
func (*DesiredStateSnapshot) Descriptor() ([]byte, []int) {
	return file_dexon_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DesiredStateSnapshot) GetVms() []*VMSpec {
	if x != nil {
		return x.Vms
	}
	return nil
}

// CreateVM/DeleteVM double as incremental desired-state updates: the
// agent applies the change to its cache as part of executing the command,
// so the cache and the executed action can never drift from each other.
type CreateVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMSpec                `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVM) Reset() {
	*x = CreateVM{}
	mi := &file_dexon_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVM) ProtoMessage() {}

func (x *CreateVM) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVM.ProtoReflect.Descriptor instead.
func (*CreateVM) Descriptor() ([]byte, []int) {
	return file_dexon_agent_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVM) GetVm() *VMSpec {
	if x != nil {
		return x.Vm
	}
	return nil
}

type DeleteVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVM) Reset() {
	*x = DeleteVM{}
	mi := &file_dexon_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVM) ProtoMessage() {}

func (x *DeleteVM) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVM.ProtoReflect.Descriptor instead.
func (*DeleteVM) Descriptor() ([]byte, []int) {
	return file_dexon_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type VMSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Vcpus         int32                  `protobuf:"varint,2,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	DiskImage     string                 `protobuf:"bytes,4,opt,name=disk_image,json=diskImage,proto3" json:"disk_image,omitempty"`
	NetworkId     string                 `protobuf:"bytes,5,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMSpec) Reset() {
	*x = VMSpec{}
	mi := &file_dexon_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMSpec) ProtoMessage() {}

func (x *VMSpec) ProtoReflect() protoreflect.Message {
	mi := &file_dexon_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMSpec.ProtoReflect.Descriptor instead.
func (*VMSpec) Descriptor() ([]byte, []int) {
	return file_dexon_agent_proto_rawDescGZIP(), []int{11}
}

func (x *VMSpec) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMSpec) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *VMSpec) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *VMSpec) GetDiskImage() string {
	if x != nil {
		return x.DiskImage
	}
	return ""
}

func (x *VMSpec) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

var File_dexon_agent_proto protoreflect.FileDescriptor

const file_dexon_agent_proto_rawDesc = "" +
	"\n" +
	"\x11dexon_agent.proto\x12\x0edexon.agent.v1\"\x99\x02\n" +
	"\fAgentMessage\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12:\n" +
	"\bregister\x18\x02 \x01(\v2\x1c.dexon.agent.v1.RegisterHostH\x00R\bregister\x129\n" +
	"\theartbeat\x18\x03 \x01(\v2\x19.dexon.agent.v1.HeartbeatH\x00R\theartbeat\x129\n" +
	"\ametrics\x18\x04 \x01(\v2\x1d.dexon.agent.v1.MetricsReportH\x00R\ametrics\x123\n" +
	"\x05drift\x18\x05 \x01(\v2\x1b.dexon.agent.v1.DriftReportH\x00R\x05driftB\t\n" +
	"\apayload\"\x85\x01\n" +
	"\fRegisterHost\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x125\n" +
	"\x16hyperthreading_enabled\x18\x03 \x01(\bR\x15hyperthreadingEnabled\"2\n" +
	"\tHeartbeat\x12%\n" +
	"\x0eunix_timestamp\x18\x01 \x01(\x03R\runixTimestamp\"m\n" +
	"\rMetricsReport\x12/\n" +
	"\x04host\x18\x01 \x01(\v2\x1b.dexon.agent.v1.HostMetricsR\x04host\x12+\n" +
	"\x03vms\x18\x02 \x03(\v2\x19.dexon.agent.v1.VMMetricsR\x03vms\"d\n" +
	"\vHostMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x124\n" +
	"\x16memory_available_bytes\x18\x02 \x01(\x03R\x14memoryAvailableBytes\"d\n" +
	"\tVMMetrics\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x03R\vmemoryBytes\"_\n" +
	"\vDriftReport\x12$\n" +
	"\x0emissing_vm_ids\x18\x01 \x03(\tR\fmissingVmIds\x12*\n" +
	"\x11unexpected_vm_ids\x18\x02 \x03(\tR\x0funexpectedVmIds\"\xcf\x01\n" +
	"\fFleetCommand\x12B\n" +
	"\bsnapshot\x18\x01 \x01(\v2$.dexon.agent.v1.DesiredStateSnapshotH\x00R\bsnapshot\x127\n" +
	"\tcreate_vm\x18\x02 \x01(\v2\x18.dexon.agent.v1.CreateVMH\x00R\bcreateVm\x127\n" +
	"\tdelete_vm\x18\x03 \x01(\v2\x18.dexon.agent.v1.DeleteVMH\x00R\bdeleteVmB\t\n" +
	"\apayload\"@\n" +
	"\x14DesiredStateSnapshot\x12(\n" +
	"\x03vms\x18\x01 \x03(\v2\x16.dexon.agent.v1.VMSpecR\x03vms\"2\n" +
	"\bCreateVM\x12&\n" +
	"\x02vm\x18\x01 \x01(\v2\x16.dexon.agent.v1.VMSpecR\x02vm\"\x1f\n" +
	"\bDeleteVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\x94\x01\n" +
	"\x06VMSpec\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05vcpus\x18\x02 \x01(\x05R\x05vcpus\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x03R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_image\x18\x04 \x01(\tR\tdiskImage\x12\x1d\n" +
	"\n" +
	"network_id\x18\x05 \x01(\tR\tnetworkId2Y\n" +
	"\fFleetManager\x12I\n" +
	"\aConnect\x12\x1c.dexon.agent.v1.AgentMessage\x1a\x1c.dexon.agent.v1.FleetCommand(\x010\x01B3Z1github.com/anandrkskd/dexon/proto/agentv1;agentv1b\x06proto3"

var (
	file_dexon_agent_proto_rawDescOnce sync.Once
	file_dexon_agent_proto_rawDescData []byte
)

func file_dexon_agent_proto_rawDescGZIP() []byte {
	file_dexon_agent_proto_rawDescOnce.Do(func() {
		file_dexon_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dexon_agent_proto_rawDesc), len(file_dexon_agent_proto_rawDesc)))
	})
	return file_dexon_agent_proto_rawDescData
}

var file_dexon_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_dexon_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),         // 0: dexon.agent.v1.AgentMessage
	(*RegisterHost)(nil),         // 1: dexon.agent.v1.RegisterHost
	(*Heartbeat)(nil),            // 2: dexon.agent.v1.Heartbeat
	(*MetricsReport)(nil),        // 3: dexon.agent.v1.MetricsReport
	(*HostMetrics)(nil),          // 4: dexon.agent.v1.HostMetrics
	(*VMMetrics)(nil),            // 5: dexon.agent.v1.VMMetrics
	(*DriftReport)(nil),          // 6: dexon.agent.v1.DriftReport
	(*FleetCommand)(nil),         // 7: dexon.agent.v1.FleetCommand
	(*DesiredStateSnapshot)(nil), // 8: dexon.agent.v1.DesiredStateSnapshot
	(*CreateVM)(nil),             // 9: dexon.agent.v1.CreateVM
	(*DeleteVM)(nil),             // 10: dexon.agent.v1.DeleteVM
	(*VMSpec)(nil),               // 11: dexon.agent.v1.VMSpec
}
var file_dexon_agent_proto_depIdxs = []int32{
	1,  // 0: dexon.agent.v1.AgentMessage.register:type_name -> dexon.agent.v1.RegisterHost
	2,  // 1: dexon.agent.v1.AgentMessage.heartbeat:type_name -> dexon.agent.v1.Heartbeat
	3,  // 2: dexon.agent.v1.AgentMessage.metrics:type_name -> dexon.agent.v1.MetricsReport
	6,  // 3: dexon.agent.v1.AgentMessage.drift:type_name -> dexon.agent.v1.DriftReport
	4,  // 4: dexon.agent.v1.MetricsReport.host:type_name -> dexon.agent.v1.HostMetrics
	5,  // 5: dexon.agent.v1.MetricsReport.vms:type_name -> dexon.agent.v1.VMMetrics
	8,  // 6: dexon.agent.v1.FleetCommand.snapshot:type_name -> dexon.agent.v1.DesiredStateSnapshot
	9,  // 7: dexon.agent.v1.FleetCommand.create_vm:type_name -> dexon.agent.v1.CreateVM
	10, // 8: dexon.agent.v1.FleetCommand.delete_vm:type_name -> dexon.agent.v1.DeleteVM
	11, // 9: dexon.agent.v1.DesiredStateSnapshot.vms:type_name -> dexon.agent.v1.VMSpec
	11, // 10: dexon.agent.v1.CreateVM.vm:type_name -> dexon.agent.v1.VMSpec
	0,  // 11: dexon.agent.v1.FleetManager.Connect:input_type -> dexon.agent.v1.AgentMessage
	7,  // 12: dexon.agent.v1.FleetManager.Connect:output_type -> dexon.agent.v1.FleetCommand
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_dexon_agent_proto_init() }
func file_dexon_agent_proto_init() {
	if File_dexon_agent_proto != nil {
		return
	}
	file_dexon_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Metrics)(nil),
		(*AgentMessage_Drift)(nil),
	}
	file_dexon_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*FleetCommand_Snapshot)(nil),
		(*FleetCommand_CreateVm)(nil),
		(*FleetCommand_DeleteVm)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dexon_agent_proto_rawDesc), len(file_dexon_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dexon_agent_proto_goTypes,
		DependencyIndexes: file_dexon_agent_proto_depIdxs,
		MessageInfos:      file_dexon_agent_proto_msgTypes,
	}.Build()
	File_dexon_agent_proto = out.File
	file_dexon_agent_proto_goTypes = nil
	file_dexon_agent_proto_depIdxs = nil
}
