// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: dexon_agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetManager_Connect_FullMethodName = "/dexon.agent.v1.FleetManager/Connect"
)

// FleetManagerClient is the client API for FleetManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FleetManager is the agent-facing service. Agents dial in and hold a
// single long-lived bidirectional stream open for their entire lifetime.
// The agent never decides desired state -- it only reports what it
// observes and executes commands it is given.
type FleetManagerClient interface {
	// Connect is the one persistent stream per agent. The agent sends the
	// first AgentMessage (Register) to open it; both sides then push
	// messages independently for as long as the connection lives.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, FleetCommand], error)
}

type fleetManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetManagerClient(cc grpc.ClientConnInterface) FleetManagerClient {
	return &fleetManagerClient{cc}
}

func (c *fleetManagerClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, FleetCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetManager_ServiceDesc.Streams[0], FleetManager_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, FleetCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_ConnectClient = grpc.BidiStreamingClient[AgentMessage, FleetCommand]

// FleetManagerServer is the server API for FleetManager service.
// All implementations must embed UnimplementedFleetManagerServer
// for forward compatibility.
//
// FleetManager is the agent-facing service. Agents dial in and hold a
// single long-lived bidirectional stream open for their entire lifetime.
// The agent never decides desired state -- it only reports what it
// observes and executes commands it is given.
type FleetManagerServer interface {
	// Connect is the one persistent stream per agent. The agent sends the
	// first AgentMessage (Register) to open it; both sides then push
	// messages independently for as long as the connection lives.
	Connect(grpc.BidiStreamingServer[AgentMessage, FleetCommand]) error
	mustEmbedUnimplementedFleetManagerServer()
}

// UnimplementedFleetManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetManagerServer struct{}

func (UnimplementedFleetManagerServer) Connect(grpc.BidiStreamingServer[AgentMessage, FleetCommand]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedFleetManagerServer) mustEmbedUnimplementedFleetManagerServer() {}
func (UnimplementedFleetManagerServer) testEmbeddedByValue()                      {}

// UnsafeFleetManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetManagerServer will
// result in compilation errors.
type UnsafeFleetManagerServer interface {
	mustEmbedUnimplementedFleetManagerServer()
}

func RegisterFleetManagerServer(s grpc.ServiceRegistrar, srv FleetManagerServer) {
	// If the following call panics, it indicates UnimplementedFleetManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetManager_ServiceDesc, srv)
}

func _FleetManager_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetManagerServer).Connect(&grpc.GenericServerStream[AgentMessage, FleetCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_ConnectServer = grpc.BidiStreamingServer[AgentMessage, FleetCommand]

// FleetManager_ServiceDesc is the grpc.ServiceDesc for FleetManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dexon.agent.v1.FleetManager",
	HandlerType: (*FleetManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _FleetManager_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dexon_agent.proto",
}
